import { Navbar } from "@/components/common";
import { routes } from "@/configs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React, { type ReactNode } from "react";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): ReactNode {
  return (
    <html lang="en">
      <body className={` ${inter.className} bg-dark text-light`}>
        <Providers>
          {children}
          <Navbar links={Object.values(routes)} />
        </Providers>
      </body>
    </html>
  );
}
